### ISSUE TITLE
error Couldn't find a package.json file in "/opt/conda/lib/python3.6/site-packages/wger"

### ISSUE THREAD

**Issue by alex9434** [wger-project/wger#1115]
## Steps to Reproduce

I want to run wger using conda pypy in docker. I am using the following dockerfile:
```
FROM	docker.io/mambaorg/micromamba:0.25-bullseye-slim

ENV	PYTHONDONTWRITEBYTECODE 1
ENV	PYTHONUNBUFFERED 1
ENV	LANG en_US.UTF-8
ENV	LANGUAGE en_US:en
ENV	LC_ALL en_US.UTF-8

RUN	set -ex; \
	micromamba install --yes --name base --channel conda-forge --freeze-installed \
		pypy \
		pip \
		bleach~=3.3 \
		django-recaptcha~=2.0.6 \
		django~=3.1.8 \
		django-crispy-forms~=1.11 \
		django-storages~=1.11 \
		icalendar==4.0.7 \
		invoke~=1.5 \
		pillow~=8.2 \
		python-mimeparse \
		reportlab==3.5.67 \
		matplotlib>=3.1 \
		requests \
		setuptools>=18.5 \
		sphinx \
		django-cors-headers>=3.0 \
		django-filter==2.4.0 \
		djangorestframework~=3.12 \
		six>=1.12.0 \
		gunicorn~=20.1 \
		psycopg2 \
		; \
	micromamba clean --all --yes

USER	root

RUN	apt-get update; \
	apt-get install -y --no-install-recommends --no-install-suggests \	
		build-essential \
		git \
		npm \
		; \

	apt-get clean; \
	rm -rf /var/lib/apt/lists/* /root/.cache /tmp/* /var/tmp/*

RUN	npm install -g --production \
		yarn \
		sass 

USER	mambauser

ARG	MAMBA_DOCKERFILE_ACTIVATE=1

RUN	/opt/conda/bin/pypy -m pip install wger
```
1. ...docker build -t wger-demo:0.1 .
2. ...docker  run -it wger:0.1 /bin/bash
3. ...wger create-settings && wger bootstrap

**Expected results:** Setting up of demo environment

**Actual results:** Following errror message:

<details>
  <summary>Logs</summary>
```
*** Database does not exist, creating one now
Operations to perform:
  Apply all migrations: auth, authtoken, config, contenttypes, core, easy_thumbnails, exercises, gym, mailer, manager, nutrition, sessions, sites, weight
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying gym.0001_initial... OK
  Applying core.0001_initial... OK
  Applying config.0001_initial... OK
  Applying config.0002_auto_20190618_1617... OK
  Applying gym.0002_auto_20151003_1944... OK
  Applying gym.0003_auto_20151003_2008... OK
  Applying gym.0004_auto_20151003_2357... OK
  Applying gym.0005_auto_20151023_1522... OK
  Applying gym.0006_auto_20160214_1013... OK
  Applying gym.0007_auto_20170123_0920... OK
  Applying gym.0008_auto_20190618_1617... OK
  Applying exercises.0001_initial... OK
  Applying manager.0001_initial... OK
  Applying manager.0002_auto_20150202_2040... OK
  Applying manager.0004_auto_20150609_1603... OK
  Applying core.0002_auto_20141225_1512... OK
  Applying core.0003_auto_20150217_1554... OK
  Applying core.0004_auto_20150217_1914... OK
  Applying core.0005_auto_20151025_2236... OK
  Applying core.0006_auto_20151025_2237... OK
  Applying core.0007_repetitionunit... OK
  Applying core.0008_weightunit... OK
  Applying core.0009_auto_20160303_2340... OK
  Applying core.0010_auto_20170403_0144... OK
  Applying core.0011_auto_20201201_0653... OK
  Applying core.0012_auto_20210210_1228... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying exercises.0002_auto_20150307_1841... OK
  Applying exercises.0003_auto_20160921_2000... OK
  Applying exercises.0004_auto_20170404_0114... OK
  Applying exercises.0005_auto_20190618_1617... OK
  Applying exercises.0006_auto_20201203_0203... OK
  Applying exercises.0007_auto_20201203_1042... OK
  Applying exercises.0008_exercisebase... OK
  Applying exercises.0009_auto_20201211_0139... OK
  Applying exercises.0010_auto_20201211_0205... OK
  Applying exercises.0011_auto_20201214_0033... OK
  Applying exercises.0012_auto_20210327_1219... OK
  Applying mailer.0001_initial... OK
  Applying mailer.0002_auto_20190618_1617... OK
  Applying mailer.0003_auto_20201201_0653... OK
  Applying manager.0005_auto_20160303_2008... OK
  Applying manager.0006_auto_20160303_2138... OK
  Applying manager.0007_auto_20160311_2258... OK
  Applying manager.0008_auto_20190618_1617... OK
  Applying manager.0009_auto_20201202_1559... OK
  Applying manager.0010_auto_20210102_1446... OK
  Applying manager.0011_remove_set_exercises... OK
  Applying nutrition.0001_initial... OK
  Applying nutrition.0002_auto_20170101_1538... OK
  Applying nutrition.0003_auto_20170118_2308... OK
  Applying nutrition.0004_auto_20200819_2310... OK
  Applying nutrition.0005_logitem... OK
  Applying nutrition.0006_auto_20201201_0653... OK
  Applying nutrition.0007_auto_20201214_0013... OK
  Applying nutrition.0008_auto_20210102_1446... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying weight.0001_initial... OK
  Applying weight.0002_auto_20150604_2139... OK
  Applying weight.0003_auto_20160416_1030... OK
Installed 1 object(s) from 1 fixture(s)
Installed 16 object(s) from 1 fixture(s)
Installed 6 object(s) from 1 fixture(s)
Installed 3 object(s) from 1 fixture(s)
Installed 5 object(s) from 1 fixture(s)
Installed 7 object(s) from 1 fixture(s)
Installed 6 object(s) from 1 fixture(s)
Installed 6 object(s) from 1 fixture(s)
Installed 512 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 10 object(s) from 1 fixture(s)
Installed 16 object(s) from 1 fixture(s)
Installed 7 object(s) from 1 fixture(s)
Installed 355 object(s) from 1 fixture(s)
Installed 528 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
Installed 1 object(s) from 1 fixture(s)
*** Password for user admin was reset to 'adminadmin'
Installed 3 object(s) from 1 fixture(s)
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.03s.
yarn run v1.22.19
error Couldn't find a package.json file in "/opt/conda/lib/python3.6/site-packages/wger"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/opt/conda/bin/wger", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/site-packages/wger/__main__.py", line 40, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/opt/conda/site-packages/invoke/__init__.py", line 48, in run
    return Context().run(command, **kwargs)
  File "/opt/conda/site-packages/invoke/context.py", line 95, in run
    return self._run(runner, command, **kwargs)
  File "/opt/conda/site-packages/invoke/context.py", line 102, in _run
    return runner.run(command, **kwargs)
  File "/opt/conda/site-packages/invoke/runners.py", line 380, in run
    return self._run_body(command, **kwargs)
  File "/opt/conda/site-packages/invoke/runners.py", line 442, in _run_body
    return self.make_promise() if self._asynchronous else self._finish()
  File "/opt/conda/site-packages/invoke/runners.py", line 509, in _finish
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke bootstrap'
```
</details>

**Comment by rolandgeider** [comment]
Hi! I think the wger package from pypi might be missing some files (and is kinda old anyway). Have you tried cloning the git repo? (I'm guessing you have taken a look at how be build our images)

**Comment by alex9434** [comment]
Thank you very much. Using the git solved that problem. I was not aware that the PIP package was incomplete. Thank you so much for pointing that out.

**Comment by rolandgeider** [comment]
glad that it worked! You are definitely better served using master, while there are releases once in a while, for all intents and purposes this is a rolling release (and in any case the package should probably be fixed 😅 )
