### ISSUE TITLE
Can't use app with django axes enabled

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#1163]
It is currently not possible to connect to a wger server with the mobile app if it has django axes enabled.

Axes needs a request keyword passed when authenticating users, and this doesn't happen when using the login API endpoint: https://django-axes.readthedocs.io/en/latest/3_usage.html This is another reason to move to JWTs, but till then the easiest workaround is to simply disable the brute force login checks: `AXES_ENABLED=True`

Traceback:

```python
Internal Server Error: /api/v2/login/
Traceback (most recent call last):
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/entwicklung/wger/server/wger/core/api/views.py", line 227, in post
    if not form.is_valid():
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/contrib/auth/forms.py", line 202, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/axes/helpers.py", line 538, in inner
    return func(*args, **kwargs)
  File "/home/roland/entwicklung/wger/venv-server/lib/python3.10/site-packages/axes/backends.py", line 46, in authenticate
    raise AxesBackendRequestParameterRequired(
axes.exceptions.AxesBackendRequestParameterRequired: AxesBackend requires a request as an argument to authenticate
[25/Oct/2022 14:25:49] "POST /api/v2/login/ HTTP/1.1" 500 147459
```

**Comment by gregflynn** [comment]
Confirmed, disabled `AXES_ENABLED=False` and able to login

**Comment by rolandgeider** [comment]
Alright, I have disabled axes for the moment in master

**Comment by rolandgeider** [comment]
Should be fixed now
