### ISSUE TITLE
Non-operational deploying wger/server:latest

### ISSUE THREAD

**Issue by brandtkeller** [wger-project/wger#1286]
## Steps to Reproduce

1. Deploy the helm chart without any modifications

**Expected results:** 
Ability to hit the user interface and no errors in the logs

**Actual results:** 
See the logs below - the application is running in my kubernetes cluster but contains the errors seen below and visiting the application results in:

```bash
[29/Mar/2023 03:07:56] "GET / HTTP/1.1" 302 0
[29/Mar/2023 03:07:56] "GET /en/ HTTP/1.1" 302 0
Internal Server Error: /en/software/features
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 37, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.10/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/home/wger/src/wger/utils/context_processor.py", line 85, in processor
    get_custom_header(request),
  File "/home/wger/src/wger/utils/context_processor.py", line 126, in get_custom_header
    global_gymconfig = GymConfig.objects.get(pk=1)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
wger.config.models.gym_config.GymConfig.DoesNotExist: GymConfig matching query does not exist.
[29/Mar/2023 03:07:56] "GET /en/software/features HTTP/1.1" 500 133540
Not Found: /favicon.ico
[29/Mar/2023 03:07:57] "GET /favicon.ico HTTP/1.1" 404 4142
```

<details>
  <summary>Logs</summary>

```bash
k logs -f wger-app-86b595cf8b-gz5pp -n wger
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 12.42s.
yarn run v1.22.19
$ sass wger/core/static/scss/main.scss:wger/core/static/yarn/bootstrap-compiled.css
Done in 5.67s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/wger/src/wger/core/management/commands/set-site-url.py", line 18, in handle
    site = Site.objects.get_current()
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^

Using django's development server...
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 41 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): exercises, gallery, mailer, manager, measurements, nutrition, sessions, sites, weight.
Run 'python manage.py migrate' to apply them.
March 29, 2023 - 03:07:08
Django version 4.1.7, using settings 'settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

```

</details>

**Comment by rolandgeider** [comment]
Hi! The helm charts were contributed by the community, I have only a skin deep knowledge of how it works. However I have seen something similar with docker compose and there the error was that the application started before the database was ready. You can drop the postgres volume and make sure during the first run that the db starts first, after that it won't prevent the application from starting

**Comment by brandtkeller** [comment]
appreciate the quick response - posted the issue here to get exactly that sort of application-specific context. 

I'll look at the helm chart more carefully - as I believe the `initContainer` for the deployment should handle that - but that's a helm chart issue.

I'll give it more testing shortly and see if I can ensure the timing is correct between app and db and if it comes up healthy I will close out this issue.

Separate but related question - is the yarn install a process that could be performed during image build as opposed to image runtime (willing to open another issue)? I typically don't let my applications communicate externally for supply chain security reasons.

**Comment by rolandgeider** [comment]
> I'll look at the helm chart more carefully - as I believe the initContainer for the deployment should handle that - but that's a helm chart issue.

Alright. If I can do something, just ping me

 > Separate but related question - is the yarn install a process that could be performed during image build as opposed to image runtime (willing to open another issue)? I typically don't let my applications communicate externally for supply chain security reasons.

It definitely should be possible, the entrypoing bootstraps the application and downloading everything was probably the easiest way. Or perhaps we didn't want to bloat the image even more? In any case feel free to open a new ticket about this, then we can see what pros and cons it has
