### ISSUE TITLE
UnicodeDecodeError while running setup.py via "pip install -e ."

### ISSUE THREAD

**Issue by ZeroBomb** [wger-project/wger#1392]
## Steps to Reproduce

I followed the steps here, using python 3.11.3 on windows 11
https://wger.readthedocs.io/en/latest/development.html
which failed while executing
```
pip install -e .
```
**Expected results:** 
Successful install

**Actual results:**
```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\SendU\src\setup.py", line 21, in <module>
          long_description = readme.read()
                             ^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 162: character maps to <undefined>
      [end of output]
```

**Comment by ZeroBomb** [comment]
To fix this issue, I edited setup.py
I changed the line 
```Python
with open('README.md') as readme:
    long_description = readme.read()
```
to 
```Python
with open('README.md', encoding="utf8") as readme:
    long_description = readme.read()
```

Which resolved the issue.
