### ISSUE TITLE
[BUG] Exercise image not being upload

### ISSUE THREAD

**Issue by eHonnef** [wger-project/wger#1603]
I'm not able to upload a new image for the exercise, only videos are working. 

## Steps to Reproduce

1. Edit an exercise
2. Click on "Add" button to upload image, select image (jpeg, png, doesn't matter, it won't work)
3. It should make a POST request (as it does with the video), but nothing happens
4. Try to click on "Save" button, it will make a PATCH request, but also, nothing happens

## Environment

- Latest docker image.
- Nginx as reverse proxy

Also, the "Alternative Name" also doesn't appear to be working properly, I fill the field, click save, nothing happens.

**Comment by erikderzweite** [comment]
Are there any errors in the browser's console or in the docker logs? Might be a permissions issue.

**Comment by eHonnef** [comment]
Unfortunately, I don't have the container running anymore, but as far as I checked, no errors reported in the container.
The thing is that the button didn't do anything.

**Comment by johan-6** [comment]
I have the same issue.
After I click the add button and selected the image, there is an error in browser's console.
By the way, I don't seen any request in network tab, might be an issue of FE?

**Attach the error log**:
```javascript
output.10f910354a3f.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
    at output.10f910354a3f.js:1:632955
    at h (output.10f910354a3f.js:1:399561)
    at Generator.<anonymous> (output.10f910354a3f.js:1:400884)
    at Generator.next (output.10f910354a3f.js:1:399971)
    at Zl (output.10f910354a3f.js:1:557482)
    at a (output.10f910354a3f.js:1:557686)
    at output.10f910354a3f.js:1:557747
    at new Promise (<anonymous>)
    at output.10f910354a3f.js:1:557626
    at output.10f910354a3f.js:1:633316
``` 
![27H_PGZMN@NO`(6}@RRJY(B](https://github.com/wger-project/wger/assets/39640500/ed6a523f-b0e5-4350-9e98-aa96065874c2)

**Comment by seyfeb** [comment]
Same issue here. After selecting an image to be uploaded an error is logged in Firefox:

```
Uncaught (in promise) TypeError: t.imageData is undefined
```

wger version 2.3.0a2

**Comment by kuzi-moto** [comment]
Just wanted to chime in as I'm also running into this issue. Are there any workarounds until this is fixed? I'm new to the project so I don't know much about the inner workings yet.

**Comment by user12257** [comment]
Not sure if I interpreted "Nginx as reverse proxy" correct. I am also a year late, but maybe It's still helpful to at least some future reader.

The docker-compose file includes its own nginx. If you have a second one in front of that you need to configure it correctly. 

You can look into the nginx.conf in the config folder. 

**Client_max_body_size 100M** should be in your own nginx config too. And probably some other settings. Not the **location /static and media** part though. You don't want that twice.

**Comment by rolandgeider** [comment]
> Client_max_body_size 100M should be in you like it could be in your own nginx config too. And probably some other settings. Not the location /static and media part though. You don't want that twice.

exactly

(I'm closing the issue here, if there's still problems, please reopen)
