### ISSUE TITLE
Can't apply `0021_add_fibers_field` database migration

### ISSUE THREAD

**Issue by bbkz** [wger-project/wger#1680]
Checking all applied database changes shows `0021_add_fibers_field`, wasn't applied:

```bash
wger@wger-app-75db4ffbd8-xmglh:~/src$ python3 manage.py showmigrations

 [ ] 0021_add_fibers_field
```

<details>
  <summary>Trying to apply the change leads to the following error:</summary>

```bash
wger@wger-app-75db4ffbd8-xmglh:~/src$ python3 manage.py migrate
```

```bash
Operations to perform:
  Apply all migrations: actstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
Running migrations:
  Applying nutrition.0021_add_fibers_field...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "nutrition_i_search__f274b7_gin" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/models.py", line 1063, in database_forwards
    schema_editor.rename_index(model, old_index, new_index)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 522, in rename_index
    self.execute(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "nutrition_i_search__f274b7_gin" does not exist
```
</details>

**Comment by rolandgeider** [comment]
😭 

The index should have been created with that name in the previous migration 0020_full_text_search. Can you see how it's called in your system?

`docker compose exec db psql -h localhost -U wger  wger -c "SELECT * FROM pg_indexes WHERE tablename = 'nutrition_ingredient';"`

**Comment by bbkz** [comment]
i got the following:

```bash
 [X] 0020_full_text_search
 [ ] 0021_add_fibers_field


 schemaname |      tablename       |                 indexname                 | tablespace |                                                          indexdef                                                          
------------+----------------------+-------------------------------------------+------------+----------------------------------------------------------------------------------------------------------------------------
 public     | nutrition_ingredient | nutrition_ingredient_pkey                 |            | CREATE UNIQUE INDEX nutrition_ingredient_pkey ON public.nutrition_ingredient USING btree (id)
 public     | nutrition_ingredient | nutrition_ingredient_uuid_e2b71b48_uniq   |            | CREATE UNIQUE INDEX nutrition_ingredient_uuid_e2b71b48_uniq ON public.nutrition_ingredient USING btree (uuid)
 public     | nutrition_ingredient | nutrition_ingredient_category_id_43a6b274 |            | CREATE INDEX nutrition_ingredient_category_id_43a6b274 ON public.nutrition_ingredient USING btree (category_id)
 public     | nutrition_ingredient | nutrition_ingredient_code_0dc1cb48        |            | CREATE INDEX nutrition_ingredient_code_0dc1cb48 ON public.nutrition_ingredient USING btree (code)
 public     | nutrition_ingredient | nutrition_ingredient_code_0dc1cb48_like   |            | CREATE INDEX nutrition_ingredient_code_0dc1cb48_like ON public.nutrition_ingredient USING btree (code varchar_pattern_ops)
 public     | nutrition_ingredient | nutrition_ingredient_language_id_650dc6fd |            | CREATE INDEX nutrition_ingredient_language_id_650dc6fd ON public.nutrition_ingredient USING btree (language_id)
 public     | nutrition_ingredient | nutrition_ingredient_license_id_410f89b7  |            | CREATE INDEX nutrition_ingredient_license_id_410f89b7 ON public.nutrition_ingredient USING btree (license_id)
 public     | nutrition_ingredient | nutrition_i_name_8f538f_gin               |            | CREATE INDEX nutrition_i_name_8f538f_gin ON public.nutrition_ingredient USING gin (name)
(8 rows)
```

**Comment by rolandgeider** [comment]
ahh, so it already got the new name, mhh, weird. I will remove the rename for now, how the index is called is not important and we can alway give it a name and try to cleanup the rest later.

**Comment by bbkz** [comment]
btw what led me to the problem was the following error, maybe it is not even related?:

```bash
Internal Server Error: /api/v2/nutritionplan/

ProgrammingError at /api/v2/nutritionplan/
column nutrition_nutritionplan.goal_fibers does not exist
LINE 1: ..., "nutrition_nutritionplan"."goal_carbohydrates", "nutrition...
```

**Comment by rolandgeider** [comment]
yes, the new goals field was introduced in that migration. You can pull again, the new image has been built

**Comment by bbkz** [comment]
:pray:  Thank you.

**Comment by bbkz** [comment]
:tada: 
```bash
Performing database migrations
Operations to perform:
  Apply all migrations: actstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
Running migrations:
  Applying nutrition.0021_add_fibers_field... OK
```
