### ISSUE TITLE
Celery Beat Pod Crash Loopback caused by unfullfilled DB relation

### ISSUE THREAD

**Issue by joaodss2** [wger-project/wger#1763]
## Steps to Reproduce

1. Use Wger charts with custom values.yaml (indexed) 
2. Use Longhorn for dynamic PV/PVC provisioning
3. Celery fails to init due to DB relation constraints 

**Expected results:** 
Celery to run on startup

**Actual results:**
Crash Loopback of celery-beat 

<details>
  <summary>Logs</summary>

```
      celery beat v5.4.0 (opalescent) is starting.
ERROR 2024-09-01 18:01:55,884 signal Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f23c0a0ae60>> raised: ProgrammingError('relation "exercises_exercisebase" does not exist\nLINE 1: ...LECT "exercises_exercisebase"."id" AS "col1" FROM "exercises...\n                                                             ^\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "exercises_exercisebase" does not exist
LINE 1: ...LECT "exercises_exercisebase"."id" AS "col1" FROM "exercises...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.10/dist-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.10/dist-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/wger/src/wger/exercises/models/base.py", line 148, in check
    no_translations = cls.no_translations.all().count()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "exercises_exercisebase" does not exist
LINE 1: ...LECT "exercises_exercisebase"."id" AS "col1" FROM "exercises...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "exercises_exercisebase" does not exist
LINE 1: ...LECT "exercises_exercisebase"."id" AS "col1" FROM "exercises...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/local/lib/python3.10/dist-packages/celery/bin/celery.py", line 236, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/bin/beat.py", line 72, in beat
    return beat().run()
  File "/usr/local/lib/python3.10/dist-packages/celery/apps/beat.py", line 82, in run
    self.init_loader()
  File "/usr/local/lib/python3.10/dist-packages/celery/apps/beat.py", line 132, in init_loader
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.10/dist-packages/celery/loaders/base.py", line 110, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.10/dist-packages/celery/loaders/base.py", line 104, in import_default_modules
    raise response
  File "/usr/local/lib/python3.10/dist-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.10/dist-packages/celery/fixups/django.py", line 100, in on_import_modules
    self.worker_fixup.validate_models()
  File "/usr/local/lib/python3.10/dist-packages/celery/fixups/django.py", line 140, in validate_models
    run_checks()
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/dist-packages/django/core/checks/model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/wger/src/wger/exercises/models/base.py", line 148, in check
    no_translations = cls.no_translations.all().count()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "exercises_exercisebase" does not exist
LINE 1: ...LECT "exercises_exercisebase"."id" AS "col1" FROM "exercises...

```

</details>

<details>
  <summary>values.yaml</summary>

```
---
# App settings
app:
  # The server's timezone, for a list of possible names:
  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timezone: "Europe/Lisbon"
  global:
    image:
      registry: docker.io
      repository: wger/server
      # when tag left emtpy the Chart appversion will be taken
      # wger is developed as a rolling release
      tag: latest
      PullPolicy: Always
    annotations: {}
    replicas: 1
    securityContext:
      fsGroup: 1000
  persistence:
    # this will be overriden to `true` when nginx is enabled
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteMany
    sizeMedia: 8Gi
    sizeStatic: 8Gi
    sizeCeleryBeat: 1Gi
    annotations: {}
    existingClaim:
      enabled: false
      media: null
      static: null
      code: null
      celeryBeat: null
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  # when nginx is enabled persistent volumes are required
  # and therefore automatically enabled
  nginx:
    enabled: true
    image: nginx:stable
    imagePullPolicy: IfNotPresent
  django:
    secret:
      name: django
    cache:
      # in seconds - 60*60*24*15, 15 Days
      timeout: 1296000
  #
  # JWT auth
  jwt:
    secret:
      name: jwt
    # The lifetime duration of the access token, in minutes
    accessTokenLifetime: 10
    # The lifetime duration of the refresh token, in hours
    refreshTokenLifetime: 24
  #
  # Brute force login attacks
  # https://django-axes.readthedocs.io/en/latest/index.html
  axes:
    enabled: false
    lockoutParameters: "ip_address"
    failureLimit: 10
    # in minutes
    cooloffTime: 30
    # number of reverse proxies involved
    ipwareProxyCount: 0
    # order of magnitude from last proxy for the real ip
    ipwareMetaPrecedenceOrder: "HTTP_X_FORWARDED_FOR,REMOTE_ADDR"

#
# celery synchronisation
celery:
  enabled: true
  annotations: {}
  replicas: 1
  replicasWorker: 1
  securityContext:
    fsGroup: 1000
  syncExercises: true
  syncImages: true
  syncVideos: true
  # Where to download ingredient and their images if they are not known locally.
  # Possible values OFF, WGER. Note that it is recommended to keep this as WGER
  # so that we don't overwhelm the Open Food Facts servers. Needs to have USE_CELERY
  # set to true
  ingredientsFrom: WGER
  # flower the webinterface for celery
  flower:
    enabled: false
    secret:
      name: null
      password: null

ingress:
  enabled: true
  ingressClassName: internet-nginx
  url: #####
  tls: true
  annotations: {}

service:
  annotations: {}
  type: ClusterIP
  port: 8000

# PostgreSQL Settings for groundhog2k chart. Only a minimum has been specified below.
# For more options, see https://github.com/groundhog2k/helm-charts/tree/master/charts/postgres
postgres:
  # Note: keep these variables present as the wger chart uses them for the deployment
  # the superuser and user settings will be saved into a secret
  enabled: true
  # changes to the superuser and userDatabase passwords will update
  # the secret where they are save in
  settings:
    superuser:
      value: postgres
    superuserPassword:
      value: postgres
  userDatabase:
    name:
      value: wger
    user:
      value: wger
    password:
      value: wger
  # the user from the user database will be turned into a superuser
  # some database migration in django requires this
  # otherwise it was not able to create the database
  extraScripts: wger-pg-init
  service:
    port: 5432
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ## Storage parameters
  storage:
    ##  Set persistentVolumenClaimName to reference an existing PVC
    persistentVolumeClaimName:
    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    requestedSize: 8Gi
    ## the storage class name
    className:

# Redis Settings for groundhog2k chart. Only a minimum has been specified below.
# For more options, see https://github.com/groundhog2k/helm-charts/tree/master/charts/redis
redis:
  # Note: keep these variables present as the chart uses them for the Deployment
  enabled: true
  # auth: is used in wger-helm-charts to auto-create a secret for redis
  #
  # if you enable auth it will create new secret from auth.password
  # if auth.password is missing it will randomly generate one.
  #
  # to enable authentication in the redis container, you need
  # to enable the env and args mentioned below
  auth:
    enabled: false
    # default no password set, this will randomly create
    # one upon first installation
    # password: XXXXXXXXXXXXXXXXXX
  # Uncomment the following to enable password authentication:
  # # Additional environment variables (Redis server and Sentinel)
  # env:
  #   - name: REDIS_PASSWORD
  #     valueFrom:
  #       secretKeyRef:
  #         name: redis
  #         key: redis-password
  # # Arguments for the container entrypoint process (Redis server)
  # args:
  #   - "--requirepass $(REDIS_PASSWORD)"
  storage:
    ##  Set persistentVolumenClaimName to reference an existing PVC
    persistentVolumeClaimName:
    ## Alternative set requestedSize to define a size for a dynmaically created PVC
    ## five times (5x) the amount of memory (RAM)
    requestedSize: 10Gi
    ## the storage class name
    className:
  service:
    serverPort: 6379

```
</details>

**Comment by joaodss2** [comment]
I looked further into the issue and found that the issue is probably related to the wger-app not being able to initiate the database

´´´
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/wger/src
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: wger
  Building editable for wger (pyproject.toml): started
  Building editable for wger (pyproject.toml): finished with status 'done'
  Created wheel for wger: filename=wger-2.3.0a2-py3-none-any.whl size=17240 sha256=99b2077ca80f648606558212037dfbbae7bd526be205de92e5ad8eb9453655d8
  Stored in directory: /tmp/pip-ephem-wheel-cache-hbmypyl1/wheels/bb/de/68/a0b92a2822ee4f4e652bee9bccfb05e9a11dec0fbf14501163
Successfully built wger
Installing collected packages: wger
  Attempting uninstall: wger
    Found existing installation: wger 2.3.0a2
    Uninstalling wger-2.3.0a2:
      Successfully uninstalled wger-2.3.0a2
Successfully installed wger-2.3.0a2
*** Database does not exist, creating one now
[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0mactstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
[36;1mRunning migrations:[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 1: CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIM...
                     ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 70, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 451, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/schema.py", line 45, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: permission denied for schema public
LINE 1: CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIM...
                     ^

´´´

Apparently something to do with Insufficient permissions

**Comment by joaodss2** [comment]
Solved the issue by having setting the django secret, additionally added a comment to make this clearer, ideally i would this secret be a single kind and feed the secret to both django and postgres

**Comment by joaodss2** [comment]
nvm...
