### ISSUE TITLE
Please help! My wger instance crashed and I did not backup recently

### ISSUE THREAD

**Issue by SuperDarius-git** [wger-project/wger#1785]
## Steps to Reproduce

1. ... Not sure what I did, but just opened the site and got error
2. ...
3. ...

**Expected results:** 
Normal web interface
**Actual results:** 

> 
> An error occurred
> 
> There was an error on the server while processing your request. Try refreshing your browser and if that doesn't help, please try again at a later time. If the problem persists, you can seek help in ways listed below: 

<details>
  <summary>Logs</summary>
ERROR 2024-10-05 10:58:50,992 log Internal Server Error: /en/software/features
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 67, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.10/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/dist-packages/compressor/templatetags/compress.py", line 160, in render
    return self.render_compressed(
  File "/usr/local/lib/python3.10/dist-packages/compressor/templatetags/compress.py", line 123, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/usr/local/lib/python3.10/dist-packages/compressor/templatetags/compress.py", line 96, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/usr/local/lib/python3.10/dist-packages/compressor/cache.py", line 100, in get_templatetag_cachekey
    return get_cachekey("templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/compressor/base.py", line 240, in cachekey
    "".join([self.content] + self.mtimes).encode(self.charset), 12
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/compressor/base.py", line 233, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "/usr/local/lib/python3.10/dist-packages/compressor/css.py", line 23, in split_contents
    filename = self.get_filename(basename)
  File "/usr/local/lib/python3.10/dist-packages/compressor/base.py", line 191, in get_filename
    raise UncompressableFileError(
compressor.exceptions.UncompressableFileError: 'yarn/bootstrap-compiled.css' could not be found in the COMPRESS_ROOT '/home/wger/static' or with staticfiles.

```bash
```

</details>

**Comment by rolandgeider** [comment]
hi! the good news is that this seems to be only a problem with the static files, no data is lost. I'm wondering why it doesn't find the compiled css. Is there anything in the logs of the web service during startup? (docker compose logs web)

**Comment by rolandgeider** [comment]
oh wait, I see it, `Error: Cannot find module 'fs/promises'`

While that is not the cause, this happens because we always download some css and js files (and compile some others) during every start, which is a bit wasteful. I have been working on some changes to the docker images so all this happens during when building the images and they can just start (and makes them smaller due to having less dependencies). I will merge that PR tomorrow since I won't be at home today and would like to be able to react in case something gets broken with the new images

**Comment by SuperDarius-git** [comment]
Oh this is awesome,thank you so very much for fixing it! You are amazing! Testing it now as we speak...

**Comment by rolandgeider** [comment]
wait a second, the images are still building 😅 

https://github.com/wger-project/wger/actions/runs/11200488188

**Comment by SuperDarius-git** [comment]
Oh, sorry...haha...I will give it time...

**Comment by SuperDarius-git** [comment]
Should I just pull the new Docker image? Or is there something else I need to do?

**Comment by rolandgeider** [comment]
yes, just stop everything, do a `docker compose pull` and start again

**Comment by SuperDarius-git** [comment]
Thank you so much! It works again!
