### ISSUE TITLE
cannot write mode P as JPEG

### ISSUE THREAD

**Issue by elNapoli** [wger-project/wger#1791]
## Steps to Reproduce

1. Log in with your credentials.
2. In the dashboard, click on "Training" and then select "Workouts."
3. Choose a workout and attempt to add new exercises to it.
4. Search for any exercise; if you receive a 500 error response from the API, please take note of it.

**Expected results:** i was expected an array with the exercises 

**Actual results:** 500 error response

Logs

```bash


Traceback (most recent call last):
  File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/wger/.local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/wger/.local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/src/wger/exercises/api/views.py", line 378, in search
    thumbnail = t.get_thumbnail(aliases.get('micro_cropped')).url
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/easy_thumbnails/files.py", line 513, in get_thumbnail
    thumbnail = self.generate_thumbnail(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/easy_thumbnails/files.py", line 401, in generate_thumbnail
    img = engine.save_pil_image(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wger/.local/lib/python3.12/site-packages/easy_thumbnails/engine.py", line 77, in save_pil_image
    image.save(destination, format=format, **options)
  File "/home/wger/.local/lib/python3.12/site-packages/PIL/Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "/home/wger/.local/lib/python3.12/site-packages/PIL/JpegImagePlugin.py", line 642, in _save
    raise OSError(msg) from e
OSError: cannot write mode P as JPEG
```

</details>

**Comment by rolandgeider** [comment]
duplicate of https://github.com/wger-project/docker/issues/102 , closing here

On what hardware are you running the stack?
