### ISSUE TITLE
Internal Server Error (500) when trying to add exercises to workout on mobile

### ISSUE THREAD

**Issue by mrubacky** [wger-project/wger#227]
Basically the title, https://wger.de/en/workout/56374/view/?flavour=mobile is the link I was using and it throws an error when trying to add an exercise to a workout day.

![screen shot 2015-10-29 at 8 57 58 pm](https://cloud.githubusercontent.com/assets/11299726/10836054/c683f620-7e7f-11e5-8884-53ba79459835.png)

**Comment by rolandgeider** [comment]
Thanks for the report, I'll look into this. Did you get this when saving the form or does it happen already when the dialog opens?

**Comment by rolandgeider** [comment]
Here the traceback for later debugging
```python
Internal Server Error: /en/workout/set/day/27705/set/add/
Traceback (most recent call last):
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/rge/www/wger-patched/wger/manager/views/set.py", line 126, in create
    return render(request, 'set/add.html', context)
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  [...snip...]
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/template/base.py", line 674, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/rge/www/wger-patched/wger/core/templatetags/wger_extras.py", line 213, in is_checkbox
    return field.field.widget.__class__.__name__ == CheckboxInput().__class__.__name__
AttributeError: 'str' object has no attribute 'field'
```

**Comment by ibrahim45** [comment]
@rolandgeider @mrubacky Is the issue resolved?

**Comment by rolandgeider** [comment]
It hasn't happened since then (there has been some work on the wger_extras.py file where the error occurred, it might have been fixed as a side effect). I'm closing the issue, if it happens again, we can just reopen
