### ISSUE TITLE
Traceback in timer page

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#268]
Just got this per mail from wger.de:

``` python
Internal Server Error: /en/workout/xyztimer
Traceback (most recent call last):
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rge/www/venv-wger-production/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/rge/www/wger-patched/wger/manager/views/workout.py", line 317, in timer
    reps = exercise_dict['reps_list'][i]
IndexError: list index out of range
```

**Comment by rolandgeider** [comment]
Time page will be reworked, closing here
