### ISSUE TITLE
Permission problems for gym users

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#279]
Reported by user, t's not possible to edit a user belonging to a gym, it seems this happens only if the user registered himself (as opposed to being added by an admin). Opening `/de/gym/user/<id>/permission-edit` raises

``` python
TypeError at /de/gym/user/9/permission-edit
__init__() got multiple values for keyword argument 'available_roles'
```

**Comment by rolandgeider** [comment]
Could not reproduce, but implemented a workaround

**Comment by LorenzoAncora** [comment]
@rolandgeider I have the same problem.
The problem remains in 9ddc79217ba54bd6e152885c268641f622d70fd3 and superior (1.9 ...):

```
Internal Server Error: /it/gym/user/2/permission-edit
2.4:55422] Traceback (most recent call last):
2.4:55422]   File "/home/wger/venv-wger/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
2.4:55422]     response = get_response(request)
2.4:55422]   File "/home/wger/venv-wger/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
2.4:55422]     response = self._get_response(request)
2.4:55422]   File "/home/wger/venv-wger/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2.4:55422]     response = self.process_exception_by_middleware(e, request)
2.4:55422]   File "/home/wger/venv-wger/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2.4:55422]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2.4:55422]   File "/home/wger/wger/wger/gym/views/gym.py", line 271, in gym_permissions_user_edit
2.4:55422]     available_roles=form_group_permission)
2.4:55422] TypeError: __init__() got multiple values for argument 'available_roles'
```

Env: ARM64; Debian GNU/Linux; PostgreSQL backend.

**Comment by paulcalabro** [comment]
Just experienced this error myself while modifying a user of a gym who self-registered:

```
[Wed Sep 25 03:09:07.341971 2019] [wsgi:error] [pid 8:tid 139920890009344] Internal Server Error: /en/gym/user/2/permission-edit
[Wed Sep 25 03:09:07.342001 2019] [wsgi:error] [pid 8:tid 139920890009344] Traceback (most recent call last):
[Wed Sep 25 03:09:07.342006 2019] [wsgi:error] [pid 8:tid 139920890009344]   File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
[Wed Sep 25 03:09:07.342011 2019] [wsgi:error] [pid 8:tid 139920890009344]     response = self.process_exception_by_middleware(e, request)
[Wed Sep 25 03:09:07.342015 2019] [wsgi:error] [pid 8:tid 139920890009344]   File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
[Wed Sep 25 03:09:07.342019 2019] [wsgi:error] [pid 8:tid 139920890009344]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 25 03:09:07.342023 2019] [wsgi:error] [pid 8:tid 139920890009344]   File "/home/wger/src/wger/gym/views/gym.py", line 252, in gym_permissions_user_edit
[Wed Sep 25 03:09:07.342027 2019] [wsgi:error] [pid 8:tid 139920890009344]     available_roles=form_group_permission)
[Wed Sep 25 03:09:07.342033 2019] [wsgi:error] [pid 8:tid 139920890009344] TypeError: __init__() got multiple values for argument 'available_roles'
[Wed Sep 25 03:09:07.342039 2019] [wsgi:error] [pid 8:tid 139920890009344]
[Wed Sep 25 03:09:07.355460 2019] [wsgi:error] [pid 8:tid 139920890009344] DEBUG 2019-09-25 03:09:07,355 middleware Sending X-wger-redirect
```

**Comment by teadur** [comment]
@petervanderdoes  / @rolandgeider could we re-open the issue ?

**Comment by rolandgeider** [comment]
needs to be checked

**Comment by rolandgeider** [comment]
Tested this with the current master.

- Set a system gym so that new users get assign to it
- Register
- Edit roles as needed
-> No problems

While nice, it's a bit strange since the gym logic hasn't changed at all in some time 🤷🏻‍♂️
