### ISSUE TITLE
ValueError: embedded null byte

### ISSUE THREAD

**Issue by ATSGIT** [wger-project/wger#356]
I installed wger on Ubuntu with settings described for development environment.
However, sometimes I got error "ValueError: embedded null byte" and wger stops.
For example, when adding exercises for workout, I noticed that after choosing the exercise, the repetitions was not showing, so the repetitions value was set to null when I saving the form. It seems that there is a problem with UI. 

Here is the stack trace of one situation:
```
`[17/Feb/2017 00:34:56] "GET /en/workout/set/day/5/set/add/ HTTP/1.1" 200 2609
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
[17/Feb/2017 00:35:02] "GET /api/v2/exercise/search/?language=en&term=che HTTP/1.1" 200 1075
    utility.execute()
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 54, in execute
    super(Command, self).execute(*args, **options)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 93, in handle
    self.run(**options)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.main(self.inner_run, None, options)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/utils/autoreload.py", line 333, in main
    reloader(wrapped_main_func, args, kwargs)
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/utils/autoreload.py", line 299, in python_reloader
    reloader_thread()
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/utils/autoreload.py", line 275, in reloader_thread
    change = fn()
  File "/home/ats/venv-wger/lib/python3.5/site-packages/django/utils/autoreload.py", line 205, in code_changed
    stat = os.stat(filename)
ValueError: embedded null byte
```

**Comment by rolandgeider** [comment]
Well, that's a new one :/ When I started reading this, I was hoping that you had run into some installation problems, since I moved quite a bit of stuff around yesterday. Is it always the same places where this happens or is it random?

**Comment by ATSGIT** [comment]
Not the same place and not always. I saw this error somewhere else in the Weight section.

**Comment by rolandgeider** [comment]
I couldn't reproduce this and I'm also not sure at all where that null-byte could be. The only places I could think of would be the DB and the settings files, since those are generated, but this is still very strange. Perhaps deleting the DB and bootstraping?

**Comment by rolandgeider** [comment]
I've found this [this stackoverflow thread](http://stackoverflow.com/questions/38731132/mysterious-embedded-null-byte-error). If you still get the error, you could add the debug code from the answer and see which files it complains about
