### ISSUE TITLE
Trouble installing Stable version (from PyPI)

### ISSUE THREAD

**Issue by dsk2k** [wger-project/wger#366]
Hi,

When i get to the $ wger bootstrap step in the README I get the following error:
```
`Traceback (most recent call last):
  File "/home/dsk2k/wger/venv-django/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 286, in run
    self._parse(argv)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 352, in _parse
    self.load_collection()
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/program.py", line 500, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/wger/tasks.py", line 283, in <module>
    @task
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 275, in task
    return Task(args[0], **kwargs)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 61, in __init__
    self.positional = self.fill_implicit_positionals(positional)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 152, in fill_implicit_positionals
    args, spec_dict = self.argspec(self.body)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/tasks.py", line 147, in argspec
    raise TypeError("Tasks must have an initial Context argument!")
TypeError: Tasks must have an initial Context argument!
Traceback (most recent call last):
  File "/home/dsk2k/wger/venv-django/bin/wger", line 11, in <module>
    sys.exit(main())
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/wger/__main__.py", line 36, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/context.py", line 70, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/runners.py", line 259, in run
    return self._run_body(command, **kwargs)
  File "/home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/invoke/runners.py", line 399, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke --root /home/dsk2k/wger/venv-django/local/lib/python2.7/site-packages/wger/wger bootstrap'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)
`
```

What's wrong here?

**Comment by rolandgeider** [comment]
That is a problem with a newer version of the ``invoke`` package, the requirements file for the pypi version seems to just use the latest one. You _might_ be able to fix this by activating the virtualenv and doing a ``pip install invoke==0.14.0``. In any case, I plan to release version 1.8 of wger the next days

**Comment by rolandgeider** [comment]
1.8 was just released, the package from pypi should also work better. If you are still getting errors, just re open this issue
