### ISSUE TITLE
Issue with development version installation

### ISSUE THREAD

**Issue by mpena2099** [wger-project/wger#385]
Hi! I have an issue:

```
$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    setup_django_environment(get_user_config_path('wger', 'settings.py'))
  File "/Users/mauriciopena/Desktop/django/wger/wger/tasks.py", line 384, in setup_django_environment
    django.setup()
  File "/Users/mauriciopena/Desktop/django/wger/venv/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/mauriciopena/Desktop/django/wger/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/mauriciopena/Desktop/django/wger/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/mauriciopena/Desktop/django/wger/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings'

```

Installation process, after git clone:

```
$cd wger
$python3 -m venv venv
$source venv/bin/activate
$pip install -r requirements_devel.txt
$python setup.py develop
$wger create_settings --settings-path /Users/mauriciopena/Desktop/django/wger/wger/settings.py --database-path /Users/mauriciopena/Desktop/django/wger/wger/database.sqlite
$wger bootstrap --settings-path /Users/mauriciopena/Desktop/django/wger/wger/settings.py --no-start-server
$python manage.py runserver

```

I guess it is the same error as https://github.com/wger-project/wger/issues/357#issuecomment-280860780, but them he installed wger with Docker...

SO: macOS Sierra.

Thanks!
Mauricio

**Comment by mpena2099** [comment]
My solution was to change de manage.py script.

From: 
```
#!/usr/bin/env python
import sys

from django.core.management import execute_from_command_line

from wger.tasks import (
    setup_django_environment,
    get_user_config_path
)

if __name__ == "__main__":

    # If user passed the settings flag ignore the default wger settings
    if not any('--settings' in s for s in sys.argv):
        setup_django_environment(get_user_config_path('wger', 'settings.py'))

    # Alternative to above
    # os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")

    execute_from_command_line(sys.argv)

```

To:
```
#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "wger.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError:
        # The above import may fail for some other reason. Ensure that the
        # issue is really that Django is missing to avoid masking other
        # exceptions on Python 2.
        try:
            import django
        except ImportError:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )
        raise
    execute_from_command_line(sys.argv)

```

But I need to know more about this issue before close it.

**Comment by petervanderdoes** [comment]
Somebody correct me if I'm wrong please :)

The application sets `DJANGO_SETTINGS_MODULE` to `settings` by default. If, like you did, created your settings in a different directory than the root of the project you need to tell django where it can find the settings.

In your example: `python manage.py runserver --settings wger.settings`

For future reference, it's important that when you run `wger create_settings --settings-path xxxx` that `xxxx` can be imported with the app, in other words, it has to be in the PATH or within the project directory structure. If it is within the directory structure you need to use the `--settings` option when your run the server.

**Comment by petervanderdoes** [comment]
One extra detail, if you start the server without `--settings` it will also search for the settings file in one other place namely:

#### Windows
- APPDATA path

#### Others
- `~/.config/wger`

**Comment by mpena2099** [comment]
@petervanderdoes, OK I changed:

```
$wger create_settings --settings-path /Users/mauriciopena/Desktop/django/wger/wger/settings.py --database-path /Users/mauriciopena/Desktop/django/wger/wger/database.sqlite
$wger bootstrap --settings-path /Users/mauriciopena/Desktop/django/wger/wger/settings.py --no-start-server
```

To:

```
$wger create_settings --settings-path /Users/mauriciopena/Desktop/django/wger/settings.py --database-path /Users/mauriciopena/Desktop/django/wger/database.sqlite
$wger bootstrap --settings-path /Users/mauriciopena/Desktop/django/wger/settings.py --no-start-server
```

And now it works, with no modification. I don't know why but it doesn't works on my first attempt to install de develop code...

Thanks!
