### ISSUE TITLE
Stuck on install

### ISSUE THREAD

**Issue by XMineAnShineX** [wger-project/wger#397]
Im trying to install wger on rasbian Jessie and I keep getting this error when I run pip install wger.

ally-managed_ --compile:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named packaging.version

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-OXl7aL/reportlab/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LV_Hqh-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-OXl7aL/reportlab
Storing debug log for failure in /root/.pip/pip.log

**Comment by rolandgeider** [comment]
Hi there! Thanks for reporting this. It seems you have run into https://github.com/pypa/setuptools/issues/937

Can you try to upgrade pip and setuptools?

**Comment by XMineAnShineX** [comment]
I now get:

Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 273, in run
    self._parse(argv)
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 333, in _parse
    self.load_collection()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 481, in load_collection
    coll = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/local/lib/python2.7/dist-packages/invoke/loader.py", line 53, in load
    module = imp.load_module(name, fd, path, desc)
  File "/usr/local/lib/python2.7/dist-packages/wger/tasks.py", line 39, in <module>
    import django
ImportError: No module named django
Traceback (most recent call last):
  File "/usr/local/bin/wger", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/wger/__main__.py", line 36, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/usr/local/lib/python2.7/dist-packages/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/context.py", line 60, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/runners.py", line 256, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/runners.py", line 396, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke bootstrap'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)

**Comment by XMineAnShineX** [comment]
as well as:
*** No settings given, using /home/pi/.config/wger/settings.py
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 274, in run
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/invoke/program.py", line 389, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python2.7/dist-packages/invoke/executor.py", line 113, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wger/tasks.py", line 62, in start
    setup_django_environment(settings_path)
  File "/usr/local/lib/python2.7/dist-packages/wger/tasks.py", line 385, in setup_django_environment
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressor
Traceback (most recent call last):
  File "/usr/local/bin/wger", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/wger/__main__.py", line 36, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/usr/local/lib/python2.7/dist-packages/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/context.py", line 60, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/runners.py", line 256, in run
    return self._run_body(command, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/invoke/runners.py", line 396, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke start'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)

**Comment by DandyDeveloper** [comment]
@XMineAnShineX Did you get anywhere with this? Is this still outstanding?

**Comment by XMineAnShineX** [comment]
@DandyDeveloper I haven't figured it out i tried the above and it never worked.

**Comment by DandyDeveloper** [comment]
@XMineAnShineX I actually think this is just because you're missing the compressor module: 

```
ImportError: No module named compressor
```

This is then trying to exit nicely, but falling over for some weird reason. 

Are you using Django version 1.8+??? As compressor should be part of Django by default. 

I would recommend trying running this under a virtualenv `virtualenv env` -> `source env/bin/activate` then try running through the installation again for us. Let me know how you get on.

**Comment by JosephMeli** [comment]
I had a similar Issue, 
I received error messages saying that I needed to use a version of Django in between 1.9 and 1.10. So I installed 1.9. Then I realized that there was a package leftover call Django-filter, this was set to be version 2.0 which is not compatible with the version of Django we need for wger. So I downgraded Django-filter to version 1.0. Hope this helps.

**Comment by rolandgeider** [comment]
The required versions have been updated in the meantime, I'm closing this issue but feel free to reopen it
