### ISSUE TITLE
PyPI install guide does not work.

### ISSUE THREAD

**Issue by ksalaba** [wger-project/wger#447]
I cannot install via pip install wger. 

I was following the install instructions. I am installing it in my /opt/venv/ folder location
`Stable version (from PyPI)
Install the necessary packages and their dependencies in a virtualenv

$ sudo apt-get install python3-dev python-virtualenv nodejs nodejs-legacy npm libjpeg8-dev zlib1g-dev

$ virtualenv venv-django

$ source venv-django/bin/activate

$ pip install wger`

```
`(venv-django)` KSalaba@ /opt/venv $ pip install wger
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting wger
  Using cached https://www.piwheels.org/simple/wger/wger-1.8-py2.py3-none-any.whl
Collecting Django<1.10,>=1.9
  Using cached https://files.pythonhosted.org/packages/a6/ee/6dfd9e8e0d61ab22ed09c6c8f6ae5a4ad0d3bf07bca9124fb5a087f876df/Django-1.9.13-py2.py3-none-any.whl
Collecting bleach
  Using cached https://www.piwheels.org/simple/bleach/bleach-3.1.0-py2.py3-none-any.whl
Collecting django-mobile
  Using cached https://files.pythonhosted.org/packages/db/0e/956f3070bbfa00ba66839710dbefcea81193a6710a759ea5c3e0947f8c21/django-mobile-0.7.0.tar.gz
Collecting django-bootstrap-breadcrumbs
  Using cached https://files.pythonhosted.org/packages/0e/c1/67fbe6d1480ab75b86c7111ddbecc8084a3f5d3946a6f3291c8ddad4b6cf/django_bootstrap_breadcrumbs-0.9.1-py2-none-any.whl
Collecting django-formtools<1.1,>=1.0
  Using cached https://files.pythonhosted.org/packages/c7/14/a1b162c1ceeba8b5276fb0905d3bfdb996b2fdaa8279ff26a677a7259727/django_formtools-1.0-py2.py3-none-any.whl
Collecting django-compressor
  Using cached https://www.piwheels.org/simple/django-compressor/django_compressor-2.3-py2.py3-none-any.whl
Collecting django-bower
  Using cached https://files.pythonhosted.org/packages/e6/bc/f6869ec6c1b64cbed37d06d65306bdbdb4692f3cba8c23251b253887df9c/django_bower-5.2.0-py2-none-any.whl
Collecting django-recaptcha
  Using cached https://files.pythonhosted.org/packages/19/c6/38dafe2b2cdab0b73d31446640c864342f1e0aa00b2995a3fbe59e758e60/django_recaptcha-2.0.5-py2.py3-none-any.whl
Collecting sphinx
  Using cached https://www.piwheels.org/simple/sphinx/Sphinx-2.1.1-py2.py3-none-any.whl
ERROR: Package 'Sphinx' requires a different Python: 2.7.16 not in '>=3.5'

```
I can install it via pip3 install wger, however when I try to bootstrap I get the following error

```
`$ wger bootstrap
*** Creating settings file at /home/ksalaba/.config/wger
*** Database does not exist, creating one now
Operations to perform:
  Apply all migrations: weight, authtoken, gym, sessions, core, admin, exercises, email, tastypie, auth, nutrition, manager, contenttypes, config, sites, easy_thumbnails
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying authtoken.0001_initial... OK
  Applying gym.0001_initial... OK
  Applying core.0001_initial... OK
  Applying config.0001_initial... OK
  Applying exercises.0001_initial... OK
  Applying manager.0001_initial... OK
  Applying manager.0002_auto_20150202_2040... OK
  Applying manager.0004_auto_20150609_1603... OK
  Applying core.0002_auto_20141225_1512... OK
  Applying core.0003_auto_20150217_1554... OK
  Applying core.0004_auto_20150217_1914... OK
  Applying core.0005_auto_20151025_2236... OK
  Applying core.0006_auto_20151025_2237... OK
  Applying core.0007_repetitionunit... OK
  Applying core.0008_weightunit... OK
  Applying core.0009_auto_20160303_2340... OK
  Applying easy_thumbnails.0001_initial... OK
  Applying easy_thumbnails.0002_thumbnaildimensions... OK
  Applying gym.0002_auto_20151003_1944... OK
  Applying gym.0003_auto_20151003_2008... OK
  Applying gym.0004_auto_20151003_2357... OK
  Applying email.0001_initial... OK
  Applying exercises.0002_auto_20150307_1841... OK
  Applying exercises.0003_auto_20160921_2000... OK
  Applying gym.0005_auto_20151023_1522... OK
  Applying gym.0006_auto_20160214_1013... OK
  Applying gym.0007_auto_20170123_0920... OK
  Applying manager.0005_auto_20160303_2008... OK
  Applying manager.0006_auto_20160303_2138... OK
  Applying manager.0007_auto_20160311_2258... OK
  Applying nutrition.0001_initial... OK
  Applying nutrition.0002_auto_20170101_1538... OK
  Applying nutrition.0003_auto_20170118_2308... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying tastypie.0001_initial... OK
  Applying weight.0001_initial... OK
  Applying weight.0002_auto_20150604_2139... OK
  Applying weight.0003_auto_20160416_1030... OK
Installed 1 object(s) from 1 fixture(s)
Installed 12 object(s) from 1 fixture(s)
Installed 6 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: no such table: gym_gym__old

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ksalaba/.local/bin/invoke", line 10, in <module>
    sys.exit(program.run())
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/program.py", line 274, in run
    self.execute()
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/program.py", line 389, in execute
    executor.execute(*self.tasks)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/executor.py", line 113, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/wger/tasks.py", line 109, in bootstrap
    load_fixtures(context, settings_path=settings_path)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/wger/tasks.py", line 249, in load_fixtures
    call_command("loaddata", path + "users.json")
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 106, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 287, in check_constraints
    column_name, referenced_column_name, column_name, referenced_column_name))
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: Problem installing fixtures: no such table: gym_gym__old
Traceback (most recent call last):
  File "/home/ksalaba/.local/bin/wger", line 10, in <module>
    sys.exit(main())
  File "/home/ksalaba/.local/lib/python3.7/site-packages/wger/__main__.py", line 36, in main
    run(invoke_cmd + ' '.join(args), pty=True)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/__init__.py", line 38, in run
    return Context().run(command, **kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/context.py", line 60, in run
    return runner_class(context=self).run(command, **kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/runners.py", line 256, in run
    return self._run_body(command, **kwargs)
  File "/home/ksalaba/.local/lib/python3.7/site-packages/invoke/runners.py", line 396, in _run_body
    raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: 'invoke bootstrap'

Exit code: 1

Stdout: already printed

Stderr: n/a (PTYs have no stderr)

```

**Comment by ksalaba** [comment]
I was attempting to install this on a PI (ARMv7)

**Comment by edsoncudjoe** [comment]
Hi...
Just being nosy. It looks like a database table has not been been properly migrated.
`sqlite3.OperationalError: no such table: gym_gym__old` -  this line screams out at me.
I'm not too familiar with the codebase so I'll ask around.

**Comment by Veltarn** [comment]
Hi @ksalaba 

Be sure to properly invoke wger bootstrap with the proper options: 
`wger create-settings --settings-path <your-settings-file-path> --database-path <your-database-path>`
Then call
`wger bootstrap --settings-path <your-settings-file-path> --no-start-server`

I recently ran into this error and that was the way I fixed this error
