### ISSUE TITLE
Linting with gulp doesn't work

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#465]
Documenting this so it doesn't get lost.

At the moment, the gulp linter does not work, see https://travis-ci.org/github/wger-project/wger/jobs/698661186 (it's probably just a config/version thing).

```$ gulp lint
[19:10:52] Using gulpfile ~/build/wger-project/wger/gulpfile.js
[19:10:52] Starting 'lint'...
[19:10:52] Starting 'lint-js'...
[19:10:54] 'lint-js' errored after 2.15 s
[19:10:54] Error: Failed to load config "@ljharb" to extend from.
Referenced from: /home/travis/build/wger-project/wger/node_modules/array-includes/.eslintrc
    at configMissingError (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/travis/build/wger-project/wger/node_modules/gulp-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46)```

**Comment by rolandgeider** [comment]
Linting is done via an action, closing here
