### ISSUE TITLE
Can't configure settings on docker. Everything crashes

### ISSUE THREAD

**Issue by felixsanz** [wger-project/wger#473]
I don't know if i'm doing something wrong. I have copied the settings.py and modified this:

```
DEBUG = False
TEMPLATES[0]['OPTIONS']['debug'] = False
```

but when i mount my config on `/home/wger/src/settings.py`, everything crashes and wger doesn't work.

```
Exception occurred processing WSGI script '/home/wger/src/wger/wsgi.py'.
Traceback (most recent call last):
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/wger/src/wger/core/templatetags/wger_extras.py", line 215, in render
    return self.nodelist.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/wger/venv/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/base.py", line 299, in output
    return self.handle_output(mode, filtered_output, forced)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/base.py", line 307, in handle_output
    return output_func(mode, content, forced, basename)
  File "/home/wger/venv/lib/python3.5/site-packages/compressor/base.py", line 319, in output_file
    self.storage.save(new_filepath, ContentFile(content.encode(self.charset)))
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/files/storage.py", line 63, in save
    name = self._save(name, content)
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/files/storage.py", line 222, in _save
    os.makedirs(directory)
  File "/home/wger/venv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/wger/venv/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/www/CACHE'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 284, in handle_uncaught_exception
    'request': request
  File "/usr/lib/python3.5/logging/__init__.py", line 1308, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/home/wger/venv/lib/python3.5/site-packages/django/utils/log.py", line 117, in emit
    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
  File "/home/wger/venv/lib/python3.5/site-packages/django/utils/log.py", line 120, in send_mail
    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/mail/__init__.py", line 97, in mail_admins
    mail.send(fail_silently=fail_silently)
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/wger/venv/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by rolandgeider** [comment]
Did it work before changing the settings?

**Comment by felixsanz** [comment]
> Did it work before changing the settings?

Yes. And also works without modifying those variables (revert to default)

**Comment by rolandgeider** [comment]
Another thing to take a look :) Was this the apache image?

**Comment by felixsanz** [comment]
> Another thing to take a look :) Was this the apache image?

yes

**Comment by rolandgeider** [comment]
/var/www/CACHE must be writable by the apache process, I'll fix the apache image, upload a new version and check the docs (this also only happens during debug, because during debug the CSS and JS files are not compressed)

**Comment by rolandgeider** [comment]
I have fixed this is fixed in upstream, I'll build a new image and upload it to the docker hub

**Comment by rolandgeider** [comment]
FYI, I have configured GitHub actions to automatically build and push the docker images, so everything should be always working
