### ISSUE TITLE
'python manage.py runserver' gives me 'No module named 'settings''

### ISSUE THREAD

**Issue by Zoeinfp** [wger-project/wger#477]
(venv-django) zoe@magby:~/wger$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    setup_django_environment(get_user_config_path('wger', 'settings.py'))
  File "/home/zoe/wger/wger/tasks.py", line 398, in setup_django_environment
    django.setup()
  File "/home/zoe/venv-django/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/zoe/venv-django/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/home/zoe/venv-django/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/zoe/venv-django/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
No module named 'settings'

(venv-django) zoe@magby:~/wger$ ls
AUTHORS.rst  extras       manage.py    node_modules  package-lock.json  requirements_devel.txt  setup.cfg  wger
docs         LICENSE.txt  MANIFEST.in  package.json  README.rst         requirements.txt        setup.py   wger.egg-info

(venv-django) zoe@magby:~/wger/wger$ ls
config  database.sqlite  exercises  __init__.py  __main__.py  nutrition    settings_global.py  settings.tpl  tasks.py  utils   wsgi.py
core    email            gym        locale       manager      __pycache__  settings.py         software      urls.py   weight

**Comment by Svn-Sp** [comment]
Have you run 
wger create_settings \
       --settings-path /path/to/current/folder/settings.py \
       --database-path /path/to/current/folder/database.sqlite
during installation?

**Comment by Zoeinfp** [comment]
Yes I have use ./ for the /path/.../...

**Comment by Svn-Sp** [comment]
Maybe try it with the absolute path not only ./

**Comment by rolandgeider** [comment]
Yeah, absolute paths definitely cause less trouble (you can also do something like `$(pwd)/settings.py` for less typing 😄)

**Comment by Zoeinfp** [comment]
It works with $(pwd)/settings.py
