### ISSUE TITLE
Error deleting weight unit

### ISSUE THREAD

**Issue by robertp** [wger-project/wger#640]
## Steps to Reproduce

1. Create (Add) a new weight unit
2. Select the gear control to the right of the new unit
![wger-delete](https://user-images.githubusercontent.com/57381/112774012-1f4b9400-8fed-11eb-933b-fc0d7701cf8a.png)

3. Choose Delete

## Expected results
Unit would be deleted (I don't know if a toast/acknowledgement is expected).

## Actual results
Error toast
![wger-error-toast](https://user-images.githubusercontent.com/57381/112774049-35595480-8fed-11eb-8fa5-a8e89a7c2d59.png)

## Environment
- Ubuntu 20.04
- Raspberry Pi4 (aarch64)
- SQLite
- Running django behind nginx

## Logs
```python
Internal Server Error: /en/weight-unit/7/delete
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/sites/redacted/wger/core/views/weight_units.py", line 107, in dispatch
    return super(DeleteView, self).dispatch(request, *args, **kwargs)
  File "/opt/sites/redacted/wger/utils/generic_views.py", line 308, in dispatch
    return super(WgerDeleteMixin, self).dispatch(request, *args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/opt/sites/redacted/wger/core/views/weight_units.py", line 113, in get_context_data
    context = super(DeleteView, self).get_context_data(**kwargs)
  File "/opt/sites/redacted/wger/utils/generic_views.py", line 264, in get_context_data
    context = super(WgerDeleteMixin, self).get_context_data(**kwargs)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/opt/sites/redacted/wger/utils/generic_views.py", line 276, in get_form
    form = super(WgerDeleteMixin, self).get_form(form_class)
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/edit.py", line 32, in get_form
    form_class = self.get_form_class()
  File "/home/redacted/.local/lib/python3.8/site-packages/django/views/generic/edit.py", line 96, in get_form_class
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Using ModelFormMixin (base class of DeleteView) without the 'fields' attribute is prohibited.

[29/Mar/2021 02:45:25] "GET /en/weight-unit/7/delete HTTP/1.0" 500 125447
```

**Comment by robertp** [comment]
I found: https://stackoverflow.com/questions/46701426/using-modelformmixin-without-the-fields-attribute-is-prohibited

**Comment by rolandgeider** [comment]
Good catch!! This is fixed in master now
