### ISSUE TITLE
workouts generator fails because of `comment` to `name` rename

### ISSUE THREAD

**Issue by sysadmin75** [wger-project/wger#695]
## Steps to Reproduce

1. Follow installation for development environment: https://wger.readthedocs.io/en/latest/development.html
2. run  `python generator.py workouts 4`

**Expected results:** 
```
(venv-wger) [kris@dev dummy_generator]$ python generator.py workouts 4
** Generating 4 workouts per user
   - generating for user1
   - generating for user2
   - generating for user3
```
**Actual results:** 
```
(venv-wger) [kris@dev dummy_generator]$ python generator.py workouts 4
** Generating 4 workouts per user
   - generating for user1
Traceback (most recent call last):
  File "/home/kris/Projects/github/venv-wger/wger/extras/dummy_generator/generator.py", line 291, in <module>
    workout = Workout(user=user,
  File "/home/kris/Projects/github/venv-wger/lib64/python3.9/site-packages/django/db/models/base.py", line 503, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Workout() got an unexpected keyword argument 'comment'
```

<details>
  <summary>Logs</summary>

```
```

</details>

**Comment by rolandgeider** [comment]
Good catch!
