### ISSUE TITLE
Upload exercice image doesn't show

### ISSUE THREAD

**Issue by unityweb** [wger-project/wger#72]
When I upload an image; I get a big fat error : 

The 'image' attribute has no file associated with it.

See dump:

```python
ERROR 2014-03-26 12:21:54,644 base Internal Server Error: /en/exercise/1/view/
Traceback (most recent call last):
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/bin/wger/wger/exercises/views/exercises.py", line 141, in view
    return render(request, 'exercise/view.html', template_data)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 53, in render
    return HttpResponse(loader.render_to_string(*args, **kwargs),
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 506, in render
    output = self.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 506, in render
    output = self.nodelist.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/usr/local/bin/wger/python-django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'image' attribute has no file associated with it.
```

**Comment by rolandgeider** [comment]
I haven't been able to reproduce this problem and have not heard of other users having this problem. In the meantime, there have been some changes to the settings file and as well as updates to the different libraries. Closing the issue.
