### ISSUE TITLE
AttributeError when running sync-exercises command

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#840]
Some users have reported an error when running the `sync-exercises` command. It seems that for some exercises the base could not be loaded, which should not happen. As a workaround there is currently a check that skips the exercise but we should probably find out why this happens.

This is supposed to happen on a fresh installation, but I could not reproduce it (and the docker images run the command just fine).

<details>
  <summary>Logs</summary>

```bash
wger python3 manage.py sync-exercises
*** Synchronizing categories...
done!
*** Synchronizing muscles...
done!
*** Synchronizing equipment...
done!
*** Synchronizing exercises...
Traceback (most recent call last):
  File "/home/wger/src/manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/wger/src/wger/exercises/management/commands/sync-exercises.py", line 172, in handle
    exercise.exercise_base.category_id = data['category']['id']
AttributeError: 'NoneType' object has no attribute 'category_id'
```

</details>

**Comment by rolandgeider** [comment]
The import script has been refactored a bit in the meantime, closing here
