### ISSUE TITLE
DoesNotExist at /en/software/features - Language matching query does not exist.

### ISSUE THREAD

**Issue by mirisbowring** [wger-project/wger#930]
## Steps to Reproduce

I did a clean install, following the docker guide for setting up a docker production instance (used the default docker-compose).

**Expected results:**
enter ip:port and access the WebUI with default credentials

**Actual results:**
Continuously getting a django error

<details>
  <summary>Logs</summary>

```bash
Environment:


Request Method: GET
Request URL: http://10.100.10.2/en/software/features

Django Version: 3.2.10
Python Version: 3.9.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.messages',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'storages',
 'wger.config',
 'wger.core',
 'wger.mailer',
 'wger.exercises',
 'wger.gym',
 'wger.manager',
 'wger.nutrition',
 'wger.software',
 'wger.utils',
 'wger.weight',
 'wger.gallery',
 'wger.measurements',
 'captcha',
 'django.contrib.sitemaps',
 'easy_thumbnails',
 'compressor',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_bootstrap_breadcrumbs',
 'corsheaders')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'wger.utils.middleware.JavascriptAJAXRedirectionMiddleware',
 'wger.utils.middleware.WgerAuthenticationMiddleware',
 'wger.utils.middleware.RobotsExclusionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware')



Traceback (most recent call last):
  File "/home/wger/src/wger/utils/language.py", line 54, in load_language
    language = Language.objects.get(short_name=used_language)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Language matching query does not exist.), another exception occurred:
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wger/src/wger/software/views.py", line 37, in features
    return render(request, 'features.html', context)
  File "/usr/local/lib/python3.9/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.9/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.9/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/dist-packages/django/template/base.py", line 168, in render
    with context.bind_template(self):
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/dist-packages/django/template/context.py", line 244, in bind_template
    updates.update(processor(self.request))
  File "/home/wger/src/wger/utils/context_processor.py", line 28, in processor
    language = load_language()
  File "/home/wger/src/wger/utils/language.py", line 57, in load_language
    language = Language.objects.get(short_name="en")
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /en/software/features
Exception Value: Language matching query does not exist.

```

Attached a full report:
[DoesNotExist at _en_software_features.pdf](https://github.com/wger-project/wger/files/7797751/DoesNotExist.at._en_software_features.pdf)

</details>

**At the bottom it is mentioned, that I am seeing this stack Trace because Django Debug was set to True. But the prod.env is set to False...**

**Comment by timvy** [comment]
I have this error too.

**Comment by rolandgeider** [comment]
This is very probably a duplicate of https://github.com/wger-project/docker/issues/16

Could you remove the containers and volumes, pull and try again?

**Comment by mirisbowring** [comment]
Did that but still no success.

**Comment by rolandgeider** [comment]
grrrr

can you try to do `docker-compose exec web wger bootstrap` (or `docker-compose exec web wger load-fixtures` if the first one doesn't load the data)

**Comment by timvy** [comment]
> This is very probably a duplicate of [wger-project/docker#16](https://github.com/wger-project/docker/issues/16)
> 
> Could you remove the containers and volumes, pull and try again?

Pulling the new version fixed it for me. Thanks!

**Comment by mirisbowring** [comment]
Tried pulling again today, and it seems to work now!

Thank you!
