### ISSUE TITLE
Not possible to update daily calories

### ISSUE THREAD

**Issue by rolandgeider** [wger-project/wger#938]
When trying to save the daily caloric value in the user profile, the server responds with a 404:

![image](https://user-images.githubusercontent.com/2280729/148080232-11d07c12-4e4b-4a21-ba7a-6f83c288a022.png)

![image](https://user-images.githubusercontent.com/2280729/148080209-f121a35f-8a2f-46d4-950c-eb8a25ac1824.png)

**Comment by shunnkou** [comment]
Hi, I'm running into this issue as well. Are there any workarounds to set daily calories?

Thanks!

**Comment by jeannovak** [comment]
Just installed wger and I'm unable to update daily calories as well, however the behavior I see regarding the http traffic is a bit different. I see no request being done to update the value, it just requests the user profile information and nothing more:

![image](https://user-images.githubusercontent.com/42330295/205396762-c28c9b78-1d79-45ea-9a3c-c294403c801e.png)

What I do see is an error in Console:

```output.fd9063ea7d99.js:2625 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.<anonymous> (output.fd9063ea7d99.js:2625:717)
    at fire (output.fd9063ea7d99.js:225:231)
    at Object.fireWith [as resolveWith] (output.fd9063ea7d99.js:231:181)
    at done (output.fd9063ea7d99.js:643:95)
    at XMLHttpRequest.<anonymous> (output.fd9063ea7d99.js:656:314)
```

The button 'Save total calories to profile' triggers a form called form-update-calories, shown in line 559 of /en/nutrition/calculator/calories/

Checking this form in other files, it does popup in the JS file listed in the error: output.fd9063ea7d99.js

```
$('#form-update-calories').click(function(e){e.preventDefault();$.get('/api/v2/userprofile',function(){}).done(function(userprofile){var totalCalories=$('#id_calories')[0].value;$.ajax({url:'/api/v2/userprofile/'+userprofile.results[0].user+'/',type:'PATCH',data:{calories:totalCalories}});});});
```

So it should do a PATCH request to /api/v2/userprofile. I know little about JS, but my guess is that the function is trying to get the position 0 of an index but is unable to, because apparently its undefined. 

Seems like I can request the total calories, which is used to build the request, manually via console:

`totalCalories=$('#id_calories')[0].value;
'0'
totalCalories=$('#id_calories')[0].value;
'1931'
`
So it seems like an issue getting `userprofile.results[0].user`. This field seems to be related to the function getProfileField(), which does not work for me via console, but again, I don't really know how to tshoot JS. 

this is getProfileField()

```
function getProfileField(field){
	var result;
	result=null;
	$.ajax({
		url:'/api/v2/userprofile/',type:'GET',async:false,success:function(userprofile){result=userprofile.results[field];
		}
	}
	);
	return result;
}
```

Seems like the issue is with `function(userprofile){result=userprofile.results[field];`. If anyone that understands JS can take a look at this it would be great.
